spring:
  application:
    name: Alerts-Service
  data:
    mongodb:
      #uri: mongodb+srv://opiofitson:EtnFcUECuhXVL1qx@cluster0.mzoxcjq.mongodb.net/footfreedom?retryWrites=true&w=majority
      uri: mongodb://base:Philee1@localhost:27017/alerts?authSource=admin

      
