global:
  nessage: welcome to the alert service
server:
  port: 8088
spring:
  data:
    mongodb:
      #uri: mongodb+srv://opiofitson:EtnFcUECuhXVL1qx@cluster0.mzoxcjq.mongodb.net/footfreedom?retryWrites=true&w=majority
       uri: mongodb://base:Philee1@mongodb:27017/alerts?authSource=admin

  
