global:
  message: welcome to microservices
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        includes: health, info, refresh
  endpoint:
    health:
      show-details: always
