
global:
  nessage: welcome to the missingperson service
server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://opiofitson:EtnFcUECuhXVL1qx@cluster0.mzoxcjq.mongodb.net/footfreedom?retryWrites=true&w=majority

  
