spring:
  application:
    name: Resources-Service
  data:
    mongodb:
      uri: mongodb+srv://opiofitson:EtnFcUECuhXVL1qx@cluster0.mzoxcjq.mongodb.net/footfreedom?retryWrites=true&w=majority
      
