global:
  nessage: welcome to the report incident service
server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb+srv://opiofitson:EtnFcUECuhXVL1qx@cluster0.mzoxcjq.mongodb.net/footfreedom?retryWrites=true&w=majority

  
